CREATE TABLE `BIKE` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `RIDER_ID` int(11) DEFAULT NULL,
 `NAME` varchar(45) DEFAULT NULL,
 `MAKE` varchar(45) DEFAULT NULL,
 `MODEL` varchar(45) DEFAULT NULL,
 `DESCRIPTION` varchar(45) DEFAULT NULL,
 `SINCE_DATE` datetime DEFAULT NULL,
 `LAST_MAINT_DATE` datetime DEFAULT NULL,
 `IMAGE_PATH` varchar(45) DEFAULT NULL,
 `TOTAL_FEET` int(11) DEFAULT NULL,
 `TOTAL_MILES` int(11) DEFAULT NULL,
 `TOTAL_DATE` datetime DEFAULT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `id_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


CREATE TABLE `MAINTENANCE` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `BIKE_ID` int(11) NOT NULL,
 `DATE` datetime NOT NULL,
 `DESCRIPTION` varchar(1000) NOT NULL,
 `MATERIAL` varchar(50) NOT NULL,
 `COST` decimal(5,0) NOT NULL,
 `LOCATION` varchar(45) NOT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `RIDER` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `USER_NAME` varchar(45) NOT NULL,
 `PASSWORD` varchar(45) NOT NULL,
 `FIRST_NAME` varchar(45) DEFAULT NULL,
 `LAST_NAME` varchar(45) DEFAULT NULL,
 `STRAVA_ATHELETE_ID` varchar(45) DEFAULT NULL,
 `EMAIL` varchar(100) NOT NULL,
 `PHONE` varchar(45) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `USER_NAME_UNIQUE` (`USER_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;